apps/accounts/urls.py
from django.urls import path
from .views import login_view, logout_view, signup_view

app_name = 'account'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', signup_view, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.university.urls', namespace='university')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('comment/', include('apps.comment.urls', namespace='comment')),
    path('course/', include('apps.course.urls', namespace='course')),
    path('contact/', include('apps.contact.urls', namespace='contact')),
    path('profile/', include('apps.profiles.urls', namespace='profiles')),
    path('account/', include('apps.accounts.urls', namespace='account'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.db import models

apps/accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

#
# def _login_view(request):
#     query_dict = request.POST
#     username = query_dict.get('username')
#     password = query_dict.get('password')
#     if request.method == 'POST':
#         user = authenticate(request, username=username, password=password)
#         if user is None:
#             context = {"error": "bunday foydalanuvchi mavjud emas"}
#             return render(request, 'accounts/login.html', context)
#         login(request, user)
#         return redirect('/')
#
#     return render(request, 'accounts/login.html')
#

def login_view(request):
    form = AuthenticationForm(request)
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/')
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/')
    return render(request, 'accounts/logout.html')


def signup_view(request):
    form = UserCreationForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            user = User.objects.get(username=username)
            login(request, user)
            return redirect('/')
    context = {
        'form': form
    }
    return render(request, 'accounts/register.html', context)

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block title%} Login {% endblock %}

{% block content %}

<section class="site-hero site-sm-hero overlay" data-stellar-background-ratio="0.5" style="background-image:url(images/xbig_image_2.jpg.pagespeed.ic.d0K7QMgYm1.jpg)">
<div class="container">
<div class="row align-items-center justify-content-center site-hero-sm-inner">
<div class="col-md-7 text-center">
<div class="mb-5 element-animate">
<h1 class="mb-2">Log in</h1>
<p class="bcrumb"><a href="../index-2.html">Home</a> <span class="sep ion-android-arrow-dropright px-2"></span> <span class="current">Log in</span></p>
</div>
</div>
</div>
</div>
</section>

<section class="site-section">
<div class="container">
<div class="row justify-content-center">
<div class="col-md-7">
<div class="form-wrap">
<h2 class="mb-4">Log in with your account</h2>
<form action="#" method="post">
{% csrf_token %}
{{form.as_p}}
<!--<div class="row">-->
<!--<div class="col-md-12 form-group">-->
<!--<label for="name">Username</label>-->
<!--&lt;!&ndash;<input type="text" id="name" class="form-control py-2">&ndash;&gt;-->
<!--    -->
<!--</div>-->
<!--</div>-->
<!--<div class="row mb-5">-->
<!--<div class="col-md-12 form-group">-->
<!--<label for="name">Password</label>-->
<!--<input type="password" id="name" class="form-control py-2">-->
<!--</div>-->
<!--</div>-->
<!--<div class="row">-->
<!--<div class="col-md-6 form-group">-->
<input type="submit" value="Login" class="btn btn-primary px-5 py-2">
<!--</div>-->
<!--</div>-->
</form>
</div>
</div>
</div>
</div>
</section>

{% endblock %}

templates/accounts/logout.html
{% extends 'base.html' %}

{% block title %}Logout{% endblock %}

{% block content %}

    <h4>Rostanham chiqib ketmoqchimsiiz</h4>

    <form method="post">
        {% csrf_token %}
        <button type="submit">Log out</button>
        <a href="{% url 'account:login' %}">Orqaga</a>
    </form>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block title%} Register {% endblock %}

{% block content %}

<section class="site-hero site-sm-hero overlay" data-stellar-background-ratio="0.5" style="background-image:url(images/xbig_image_2.jpg.pagespeed.ic.d0K7QMgYm1.jpg)">
<div class="container">
<div class="row align-items-center justify-content-center site-hero-sm-inner">
<div class="col-md-7 text-center">
<div class="mb-5 element-animate">
<h1 class="mb-2">Register</h1>
<p class="bcrumb"><a href="../index-2.html">Home</a> <span class="sep ion-android-arrow-dropright px-2"></span> <span class="current">Register</span></p>
</div>
</div>
</div>
</div>
</section>

<section class="site-section">
<div class="container">
<div class="row justify-content-center">
<div class="col-md-7">
<div class="form-wrap">
<h2 class="mb-5">Register new account</h2>
<form action="#" method="post">
<div class="row">
<div class="col-md-12 form-group">
<label for="name">Email Address</label>
<input type="text" id="name" class="form-control py-2">
</div>
</div>
<div class="row">
<div class="col-md-12 form-group">
<label for="name">Password</label>
<input type="password" id="name" class="form-control py-2 ">
</div>
</div>
<div class="row mb-5">
<div class="col-md-12 form-group">
<label for="name">Re-type Password</label>
<input type="password" id="name" class="form-control py-2">
</div>
</div>
<div class="row">
<div class="col-md-6 form-group">
<input type="submit" value="Register" class="btn btn-primary px-5 py-2">
</div>
</div>
</form>
</div>
</div>
</div>
</div>
</section>

{% endblock %}