apps/blog/urls.py
from django.urls import path
from .views import blog_view, blog_single

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='blog'),
    path('<int:pk>/', blog_single, name='blog-single'),
]

apps/contact/urls.py
from django.urls import path
from .views import contact
app_name = 'contact'

urlpatterns = [
    path('', contact)
]

apps/course/urls.py
from django.urls import path

app_name = 'course'

urlpatterns = [

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.university.urls', namespace='university')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('comment/', include('apps.comment.urls', namespace='comment')),
    path('course/', include('apps.course.urls', namespace='course')),
    path('contact/', include('apps.contact.urls', namespace='contact')),
    path('profile/', include('apps.profiles.urls', namespace='profiles')),
    path('account/', include('apps.accounts.urls', namespace='account'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Category(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title



class Tag(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title


class Blog(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=221)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='blog/')
    content = RichTextField()
    tags = models.ManyToManyField(Tag)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

apps/comment/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save


class Comment(models.Model):
    author = models.ForeignKey('profiles.Profile', on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True)
    post = models.ForeignKey('blog.Blog', on_delete=models.CASCADE)
    top_level_comment_id = models.IntegerField(null=True, blank=True)
    message = models.TextField()
    is_reply = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.author.full_name}s comment'

    @property
    def get_children(self):
        children = Comment.objects.filter(top_level_comment_id=self.id).exclude(id=self.id)
        return children

def comment_pre_save(instance, sender, *args, **kwargs):
    if instance.parent is not None:
        instance.is_reply = True


def comment_post_save(instance, sender, created, *args, **kwargs):
    if created:
        if instance.top_level_comment_id is None:
            top_level_comment_id = instance.id
            parent = instance
            while True and parent.parent is not None:
                top_level_comment_id = parent.parent.id
                parent = parent.parent
            instance.top_level_comment_id = top_level_comment_id
            instance.save()


pre_save.connect(comment_pre_save, sender=Comment)
post_save.connect(comment_post_save, sender=Comment)

apps/contact/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=221)
    phone = models.CharField(max_length=221)
    email = models.EmailField(max_length=221)
    message = models.TextField()

    def __str__(self):
        return self.name

apps/course/models.py
from django.db import models
from ckeditor.fields import RichTextField


def path_to_course_image(instance, filename):
    category = instance.category.title
    course = instance.title
    return '{0}/{1}/images/{2}'.format(category, course, filename)


def path_to_lesson_video(instance, filename):
    category = instance.course.category.title
    course = instance.course.title
    lesson = instance.title
    return '{0}/{1}/{2}/videos/{3}'.format(category, course, lesson, filename)


class Course(models.Model):
    author = models.ForeignKey('profiles.Profile', on_delete=models.CASCADE)
    title = models.CharField(max_length=221)
    image = models.ImageField(upload_to=path_to_course_image)
    category = models.ForeignKey('blog.Category', on_delete=models.SET_NULL, null=True)
    tags = models.ManyToManyField('blog.Tag')
    description = RichTextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class CourseDetail(models.Model):
    course = models.OneToOneField(Course, on_delete=models.CASCADE)
    detail = RichTextField()

    def __str__(self):
        return f'{self.course.title}s detail'


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length=221)
    duration = models.CharField(max_length=21)
    video = models.FileField(upload_to=path_to_lesson_video)
    description = RichTextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

apps/profiles/models.py
from django.db import models

# Create your models here.


def path_to_profile_avatar(instance, filename):
    return 'profiles/{0}/{1}'.format(instance.account.username, filename)


class Profile(models.Model):
    ROLE = (
        (0, 'Stuff'),
        (1, 'Teacher'),
        (2, 'Student'),
    )
    account = models.OneToOneField('auth.User', on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to=path_to_profile_avatar)
    role = models.IntegerField(choices=ROLE, default=2)
    bio = models.TextField()

    @property
    def full_name(self):
        result = self.account.username
        if self.account.first_name and self.account.last_name:
            result = f'{self.account.first_name} {self.account.last_name}'
        return result

    def __str__(self):
        return f'{self.account.username}s profile'

apps/contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = filed_name.capitalize()

apps/profiles/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class']='form-control'
            field.widget.attrs['placeholder']=field_name.capitalize()

apps/blog/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from .models import Blog
from apps.comment.models import Comment


def blog_view(request):
    posts = Blog.objects.all().order_by('-id')

    cat = request.GET.get('cat')
    tag = request.GET.get('tag')
    author = request.GET.get('author')
    date = request.GET.get('date')

    if cat:
        posts = posts.filter(category__title__exact=cat)

    if tag:
        posts = posts.filter(tags__title__exact=tag)

    if author:
        posts = posts.filter(author__username__exact=author)

    if date:
        posts = posts.filter(created_at__contains=date)

    context = {
        'posts': posts,
    }

    return render(request, 'blog.html', context)


def blog_single(request, pk=None):
    if request.method == "POST":
        if request.user.is_authenticated:
            message = request.POST.get('message')
            comment_id = request.POST.get('comment_id')
            top_level_comment_id = request.POST.get('top_level_comment_id')

            if message:
                comment = Comment(
                    author_id=request.user.id,
                    post_id=pk,
                    message=message
                )
                if comment_id:
                    comment.parent_id = comment_id
                if top_level_comment_id:
                    comment.top_level_comment_id = top_level_comment_id
                comment.save()
                return redirect(f'/blog/{pk}#comment-list')
        return redirect('/login/')

    if pk is not None:
        post = Blog.objects.get(id=pk)
        comments = Comment.objects.filter(is_reply=False, post_id=pk)
        context = {
            'post': post,
            'comments': comments,
        }
        return render(request, 'blog-single.html', context)
    raise Http404

apps/contact/views.py
from django.shortcuts import render
from .forms import ContactForm, Contact


# Create your views here.

def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {
        'form': form
    }
    return render(request, 'contact.html', context)

apps/course/views.py
from django.shortcuts import render

# Create your views here.

apps/profiles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .forms import ProfileForm


# Create your views here.
def profile_view(request, pk):
    user = User.objects.get(id=pk)
    form = ProfileForm(request.POST, request.FILES or None)
    if form.is_valid():
        form.save()
        return redirect('/')

    context = {
        'user': user,
        'form': form,
    }
    return render(request, 'profile.html', context)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title%}About{% endblock %}

{% block content %}


<section class="site-hero site-sm-hero overlay" data-stellar-background-ratio="0.5" style="background-image:url({% static 'images/xbig_image_2.jpg.pagespeed.ic.d0K7QMgYm1.jpg'  %})">
<div class="container">
<div class="row align-items-center justify-content-center site-hero-sm-inner">
<div class="col-md-7 text-center">
<div class="mb-5 element-animate">
<h1 class="mb-2">About Us</h1>
<p class="bcrumb"><a href="index-2.html">Home</a> <span class="sep ion-android-arrow-dropright px-2"></span> <span class="current">About Us</span></p>
</div>
</div>
</div>
</div>
</section>
{% for about in abouts %}
<section class="site-section element-animate">
<div class="container">
<div class="row">
<div class="col-md-6 order-md-2">
<div class="block-16">
<figure>
<img src="{{ about.image.url }}" alt="Image placeholder" class="img-fluid">
</figure>
</div>
</div>
<div class="col-md-6 order-md-1">
<div class="block-15">
<div class="heading">
<h2>{{ about.title }}</h2>
</div>
<div class="text mb-5">
<p>{{ about.description }}</p>
</div>
</div>
</div>
</div>
</div>
</section>
{% endfor %}

<section class="site-section pt-3 element-animate">
<div class="container">
<div class="row justify-content-center mb-5 element-animate">
<div class="col-md-7 text-center section-heading">
<h2 class="text-primary heading">School Services</h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit qui neque sint eveniet tempore sapiente.</p>
</div>
</div>
<div class="row">
{% for service in services %}
<div class="col-md-6 col-lg-3">
<div class="media block-6 d-block">
<div class="icon mb-3"><img src="{{service.service_icon.url }}" height="50px" width="50px" alt=""></div>
<div class="media-body">
<h3 class="heading">{{service.service_title}}</h3>
<p>{{ service.service_content|slice:"30"}}</p>
<p><a href="#" class="more">Read More <span class="ion-arrow-right-c"></span></a></p>
</div>
</div>
</div>
{% endfor %}
</div>
</div>
</section>

<div class="container site-section element-animate">
<div class="row justify-content-center mb-5 element-animate">
<div class="col-md-7 text-center section-heading">
<h2 class="text-primary heading">Why Choose Us</h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit qui neque sint eveniet tempore sapiente.</p>
</div>
</div>
{% for reason in reasons %}
    {% if forloop.counter0|divisibleby:2 %}
<div class="block-3 d-md-flex pt-5">
<div class="image" style="background-image:url({{reason.reason_image.url}})"></div>
<div class="text">
<h4 class="subheading">Nice text here</h4>
<h2 class="heading">{{reason.reason_title}}</h2>
<p>{{reason.reason_content}}</p>
</div>
</div>
    {% else %}
<div class="block-3 d-md-flex">
<div class="image order-2" style="background-image:url({{reason.reason_image.url}})"></div>
<div class="text order-1">
<h4 class="subheading">Nice text here</h4>
<h2 class="heading">{{reason.reason_title}}</h2>
<p>{{reason.reason_content}}</p>
</div>
</div>
</div>
{% endif %}
{% endfor %}
<div class="site-section element-animate">
<div class="container">
<div class="row justify-content-center mb-5">
<div class="col-md-7 text-center section-heading">
<h2 class="text-primary heading">Frequently Ask Questions</h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit qui neque sint eveniet tempore sapiente.</p>
</div>
</div>
<div class="row">
{% for faq in faqs %}
<div class="col-md-12">
<div class="accordion block-8" id="accordion">

<div class="accordion-item">
<h3 class="mb-0 heading">
<a class="btn-block" data-toggle="collapse" href="#collapseOne" role="button" aria-expanded="true" aria-controls="collapseOne">{{faq.question}}<span class="icon"></span></a>
</h3>
<div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
<div class="body-text">
<p>{{faq.answer}}</p>
</div>
</div>
</div>
</div>
</div>
{% endfor %}

</div>
</div>
</div>
{% include 'subscribe.html' %}

{% endblock %}

templates/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% load sidebar %}
{% block title %}Blog single{% endblock %}

{% block content %}

    <section class="site-hero site-sm-hero overlay" data-stellar-background-ratio="0.5"
             style="background-image:url({% static 'images/xbig_image_2.jpg.pagespeed.ic.d0K7QMgYm1.jpg' %})">
        <div class="container">
            <div class="row align-items-center justify-content-center site-hero-sm-inner">
                <div class="col-md-12 text-center">
                    <div class="mb-5 element-animate">
                        <h1 class="mb-2">Even the all-powerful Pointing has no control about the blind texts</h1>
                        <p class="bcrumb">by <a href="/blog/?author={{ post.author.username }}">
                            {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}
                                {{ post.author.username }}{% endif %}</a> on <a
                                href="/blog/?date={{ post.created_at|date:"Y-m-d" }}">{{ post.created_at.date }}</a></p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="site-section bg-light">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-lg-8 order-md-2 pl-lg-5">
                    <div class="row">
                        <div class="col-md-12 col-lg-12 mb-5">
                            <p class="lead">{{ post.content|safe }}</p>
                            <div class="pt-5">
                                <p>Categories: <a href="/blog/?cat={{ post.category }}">{{ post.category }}</a>, Tags:
                                    {% for obj in post.tags.all %}
                                        <a href="/blog/?tag={{ obj.title }}">#{{ obj.title }}</a>
                                    {% endfor %}


                                </p>
                            </div>
                            <div class="pt-5" id="comment-list">
                                <h3 class="mb-5">{{ post.comment_set.all.count }} Comments</h3>


                                <ul class="comment-list" >

                                    {% for comment in comments %}
                                        <li class="comment">
                                            <div class="vcard bio">
                                                {% if comment.author.avatar %}
                                                    <img src="{{ comment.author.avatar.url }}"
                                                         alt="{{ comment.author.avatar.name }}">
                                                {% endif %}
                                            </div>
                                            <div class="comment-body">
                                                <h3>{{ comment.author.full_name.title }}</h3>
                                                <div class="meta">{{ comment.created_at }}</div>
                                                <p>{{ comment.message }}</p>
                                                <p><a href="#leave_comment" data-comment_id="{{ comment.id }}" data-top_level_comment_id="{{ comment.top_level_comment_id }}" class="reply">Reply</a></p>
                                            </div>
                                            {% if comment.get_children %}
                                                <ul class="children">
                                                    {% for item in comment.get_children %}
                                                        <li class="comment">
                                                            <div class="vcard bio">
                                                                {% if item.author.avatar %}
                                                                <img src="{{ item.author.avatar.url }}"
                                                                     alt="{{ item.author.avatar.name }}">
                                                                {% endif %}
                                                            </div>
                                                            <div class="comment-body">
                                                                <h3>{{ item.author.full_name.title }} <code>replied to</code> {{ item.parent.author.full_name.title }}</h3>
                                                                <div class="meta">{{ item.created_at }}</div>
                                                                <p>{{ item.message }}</p>
                                                                <p><a href="#leave_comment" data-comment_id="{{ item.id }}" data-top_level_comment_id="{{ item.top_level_comment_id }}" class="reply">Reply</a></p>
                                                            </div>
                                                        </li>
                                                    {% endfor %}
                                                </ul>
                                            {% endif %}
                                        </li>
                                    {% endfor %}
                                </ul>


                                <div class="comment-form-wrap pt-5">
                                    <h3 class="mb-5" id="leave_comment">Leave a comment</h3>
                                    <form method="post" class="bg-light">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label for="message">Message</label>
                                            <input type="text" value="" name="comment_id" id="comment_id" hidden>
                                            <input type="text" value="" name="top_level_comment_id" id="top_level_comment_id" hidden>
                                            <textarea name="message" id="message" cols="30" rows="10"
                                                      class="form-control"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <input type="submit" value="Post Comment" class="btn btn-primary">
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 col-lg-4 order-md-1">
                    <div class="block-24 mb-5">
                        <h3 class="heading">Categories</h3>
                        {% sidebar_categories as sidebar_categories %}
                        <ul>
                            {% for category in sidebar_categories %}
                                <li><a href="/blog/?cat={{ category.title }}">{{ category.title }}
                                    <span>{{ category.course_set.all.count }}</span></a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="block-25 mb-5">
                        <div class="heading">Recent Courses</div>
                        {% sidebar_posts as sidebar_posts %}
                        <ul>
                            {% for recent in sidebar_posts %}
                                <li>
                                    <a href="/blog/{{ recent.id }}/" class="d-flex">
                                        <figure class="image mr-3">
                                            <img src="{{ recent.image.url }}" alt="{{ recent.image.name }}"
                                                 class="img-fluid">
                                        </figure>
                                        <div class="text">
                                            <h3 class="heading">{{ recent.title }}</h3>
                                            <span class="meta">Free</span>
                                        </div>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="block-26">
                        <h3 class="heading">Tags</h3>
                        {% sidebar_tags as sidebar_tags %}
                        <ul>
                            {% for tag in sidebar_tags %}
                                <li><a href="/blog/?tag={{ tag.title }}">{{ tag.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
    {% include 'subscribe.html' %}

    <script>
        let btn = document.querySelectorAll('.reply');
        let comment_id = document.querySelector('#comment_id');
        let top_level_comment_id = document.querySelector('#top_level_comment_id');

        btn.forEach(el => {
            el.addEventListener('click', () => {
                console.log('ishladi')
                comment_id.value = el.dataset.comment_id;
                top_level_comment_id.value = el.dataset.top_level_comment_id;
            })
        })

    </script>

{% endblock %}

templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% load sidebar %}
{% block title %} Blog {% endblock %}

{% block content %}

    <section class="site-hero site-sm-hero overlay" data-stellar-background-ratio="0.5"
             style="background-image:url({% static 'images/xbig_image_2.jpg.pagespeed.ic.d0K7QMgYm1.jpg' %})">
        <div class="container">
            <div class="row align-items-center justify-content-center site-hero-sm-inner">
                <div class="col-md-7 text-center">
                    <div class="mb-5 element-animate">
                        <h1 class="mb-2">Our Blog</h1>
                        <p class="bcrumb"><a href="/">Home</a> <span
                                class="sep ion-android-arrow-dropright px-2"></span> <span class="current">Blog</span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="site-section bg-light">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-lg-8 order-md-2">
                    <div class="row">
                        {% for post in posts %}
                        <div class="col-md-12 col-lg-6 mb-5">
                            <div class="block-20 ">
                                <figure>
                                    <a href="/blog/{{ post.id }}/"><img src="{{ post.image.url }}"
                                                                    alt="{{ post.image.name }}" class="img-fluid"></a>
                                </figure>
                                <div class="text">
                                    <h3 class="heading"><a href="/blog/{{ post.id }}/">{{ post.title }}</a></h3>
                                    <div class="meta">
                                        <div><a href="/blog/?date={{ post.created_at|date:'Y-m-d' }}"><span class="ion-android-calendar"></span>{{ post.created_at.date }}</a>
                                        </div>
                                        <div><a href="/blog/?author={{ post.author.get_full_name }}"><span class="ion-android-person"></span> {{ post.author.username }}</a></div>
                                        <div><a href="/blog/{{ post.id }}/#comments"><span class="ion-chatbubble"></span> 19</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="row mb-5">
                        <div class="col-md-12 text-center">
                            <div class="block-27">
                                <ul>
                                    <li><a href="#">&lt;</a></li>
                                    <li class="active"><span>1</span></li>
                                    <li><a href="#">2</a></li>
                                    <li><a href="#">3</a></li>
                                    <li><a href="#">&gt;</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 col-lg-4 order-md-1">
                    <div class="block-24 mb-5">
                        <h3 class="heading">Categories</h3>
                        {% sidebar_categories as sidebar_categories %}
                        <ul>
                            {% for category in sidebar_categories %}
                                <li><a href="/blog/?cat={{ category.title }}">{{ category.title }}
                                    <span>{{ category.course_set.all.count }}</span></a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="block-25 mb-5">
                        <div class="heading">Recent Courses</div>

                        {% sidebar_posts as sidebar_posts %}
                        <ul>
                            {% for recent in sidebar_posts %}
                                <li>
                                    <a href="/blog/{{ recent.id }}/" class="d-flex">
                                        <figure class="image mr-3">
                                            <img src="{{ recent.image.url }}" alt="{{ recent.image.name }}"
                                                 class="img-fluid">
                                        </figure>
                                        <div class="text">
                                            <h3 class="heading">{{ recent.title }}</h3>
                                            <span class="meta">Free</span>
                                        </div>
                                    </a>
                                </li>
                            {% endfor %}


                        </ul>
                    </div>
                    <div class="block-26">
                        <h3 class="heading">Tags</h3>
                        {% sidebar_tags as sidebar_tags %}
                        <ul>
                            {% for tag in sidebar_tags %}
                                <li><a href="/blog/?tag={{ tag.title }}">{{ tag.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
    {% include 'subscribe.html' %}

{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title%} contact {% endblock %}

{% block content %}

<section class="site-hero site-sm-hero overlay" data-stellar-background-ratio="0.5" style="background-image:url(images/xbig_image_2.jpg.pagespeed.ic.d0K7QMgYm1.jpg)">
<div class="container">
<div class="row align-items-center justify-content-center site-hero-sm-inner">
<div class="col-md-7 text-center">
<div class="mb-5 element-animate">
<h1 class="mb-2">Contact Us</h1>
<p class="bcrumb"><a href="index-2.html">Home</a> <span class="sep ion-android-arrow-dropright px-2"></span> <span class="current">Contact Us</span></p>
</div>
</div>
</div>
</div>
</section>

<section class="site-section element-animate">
<div class="container">
<div class="row">
<div class="col-md-8 pr-md-5">
<form action="#" method="post">
{% csrf_token %}
<div class="row">
<div class="col-md-4 form-group">
<label for="name">Name</label>
<!--<input type="text" id="name" class="form-control py-2">-->
{{ form.name }}
</div>
<div class="col-md-4 form-group">
<label for="phone">Phone</label>
<!--<input type="text" id="phone" class="form-control py-2">-->
{{ form.phone }}
</div>
<div class="col-md-4 form-group">
<label for="email">Email</label>
<!--<input type="email" id="email" class="form-control py-2">-->
 {{ form.email }}
</div>
</div>
<div class="row">
<div class="col-md-12 form-group">
<label for="message">Write Message</label>
<!--<textarea name="message" id="message" class="form-control py-2" cols="30" rows="8"></textarea>-->
{{ form.message }}
</div>
</div>
<div class="row">
<div class="col-md-6 form-group">
<input type="submit" value="Send Message" class="btn btn-primary">
</div>
</div>
</form>
</div>
<div class="col-md-4">
<div class="block-23">
<h3 class="heading mb-5">Contact Information</h3>
<ul>
<li><span class="icon ion-android-pin"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
<li><a href="#"><span class="icon ion-ios-telephone"></span><span class="text">+2 392 3929 210</span></a></li>
<li><a href="#"><span class="icon ion-android-mail"></span><span class="text"><span class="__cf_email__" data-cfemail="7910171f163900160c0b1d1614181017571a1614">[email&#160;protected]</span></span></a></li>
<li><span class="icon ion-android-time"></span><span class="text">Monday &mdash; Friday 8:00am - 5:00pm</span></li>
</ul>
</div>
</div>
</div>
</div>
</section>
{% include 'subscribe.html' %}

{% endblock %}